@@exam_db\Relational\Oracle_Database_11g\DataObjects\Structure_Type\MDSYS.SDO_GEOMETRY.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Structure_Type\XMLTYPE.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\corrected_question.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\corrected_question_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\corrected_test.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\corrected_test_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\course.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\course_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\option.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\option_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\question.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\question_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\solved_question.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\solved_question_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\solved_test.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\solved_test_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\student.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\student_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\teacher.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\teacher_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\test.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\Table\test_Constraints.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\corrected_question_corrected_test_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\corrected_question_solved_question_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\corrected_test_solved_test_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\corrected_test_student_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\option_question_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\question_test_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\solved_question_question_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\solved_question_solved_test_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\solved_test_student_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\solved_test_test_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\test_course_FK.sql
@@exam_db\Relational\Oracle_Database_11g\DataObjects\ForeignKey\test_teacher_FK.sql
